export const keywordData = {
  "#마일드화이트": [
    { id: 15, title: "마일드 화이트 사각접시 메인 디너접시 27cm (대)", price: "19,500", img: "/img/white1.jpg", detailCount: 6 },
    { id: 16, title: "마일드 화이트 원형 접시 메인 디너접시 27cm (특대)", price: "13,900", img: "/img/white2.jpg", detailCount: 5 },
    { id: 17, title: "마일드 화이트 사각 그라탕기", price: "9,900", img: "/img/white3.jpg", detailCount: 6 },
    { id: 18, title: "마일드 화이트 계란찜기 계란찜 그릇 (소) 300ml", price: "10,900", img: "/img/white4.jpg", detailCount: 6 },
    { id: 19, title: "마일드 화이트 캔디 면기", price: "10,900", img: "/img/white5.jpg", detailCount: 6 },
    { id: 20, title: "마일드 화이트 캔디 국그릇 대접", price: "5,900", img: "/img/white6.jpg", detailCount: 6 },
    { id: 21, title: "마일드 화이트 사각 초장기 소스볼 종지그릇", price: "3,900", img: "/img/white7.jpg", detailCount: 6 },
    { id: 14, title: "마일드 화이트 계란찜기 계란찜 그릇 (중) 500ml", price: "12,900", img: "/img/white8.jpg", detailCount: 5 },
    { id: 23, title: "마일드 화이트 타원 그라탕기(대)", price: "16,500", img: "/img/white9.jpg", detailCount: 6 },
  ],
  "#그릇세트": [
    { id: 24, title: "보담 2인 그릇세트(+1인추가) 21P 도자기그릇 홈세트 식기세트", price: "90,000", img: "/img/set1.jpg", detailCount: 5 },
    { id: 25, title: "라옴 6인 그릇세트 홈세트 39P", price: "178,000", img: "/img/set2.jpg", detailCount: 6 },
    { id: 26, title: "비바 4인 그릇세트 홈세트 (21P) (4color)", price: "129,000", img: "/img/set3.jpg", detailCount: 9 },
    { id: 27, title: "라피네 6인 그릇세트 홈세트 36P_블루베이지", price: "99,000", img: "/img/set4.jpg", detailCount: 7 },
    { id: 28, title: "보담 6인 그릇세트 식기세트 42P", price: "159,000", img: "/img/set5.jpg", detailCount: 5 },
    { id: 29, title: "레트로 라인 6인 홈세트 그릇세트 40P", price: "159,000", img: "/img/set6.jpg", detailCount: 9,gifIndex: 2 },
    { id: 30, title: "클래식 레이스 4인 그릇세트 홈세트 25P", price: "99,000", img: "/img/set7.jpg", detailCount: 5 },
    { id: 31, title: "블랑 웨이브 2인 그릇세트 홈세트 12P", price: "99,000", img: "/img/set8.jpg", detailCount: 9 },
    { id: 7, title: "블랑 4인 그릇세트 홈세트 27P", price: "199,000", img: "/img/set9.jpg", detailCount: 11 },
  ],
  "#선물(Gift)": [
    { id: 2, title: "[국가유산진흥원 굿즈] 선비의 멋 주안상 세트(4p)", price: "50,000", img: "/img/gift1.jpg", detailCount: 10 },
    { id: 10, title: "윈터 홀리데이세트 10p (스노우맨2인 6p+스몰디쉬4p)", price: "50,000", img: "/img/gift2.jpg", detailCount: 10 },
    { id: 35, title: "국립박물관 굿즈 신라의 미소 소스볼 3p + 수막새 수저받침 3p 세트", price: "43,000", img: "/img/gift3.jpg", detailCount: 5 },
    { id: 36, title: "링 핸들 머그 M (3color)", price: "7,900", img: "/img/gift4.jpg", detailCount: 5 },
    { id: 37, title: "튜브 핸들 머그 (3color)", price: "17,900", img: "/img/gift5.jpg", detailCount: 5 },
    { id: 38, title: "링 핸들 머그 L (3color)", price: "8,900", img: "/img/gift6.jpg", detailCount: 5 },
    { id: 39, title: "하트 머들러 (4color)", price: "4,900", img: "/img/gift7.jpg", detailCount: 5 },
    { id: 40, title: "스태킹 이중 내열 글라스 M 350ml", price: "11,900", img: "/img/gift8.jpg", detailCount: 5 },
    { id: 9, title: "윈터 스몰디쉬 4P 세트", price: "25,900", img: "/img/gift9.jpg", detailCount: 10 },
  ],
  "#유리&머그컵": [
    { id: 42, title: "스마일 맥주잔 3P", price: "31,900", img: "/img/cup1.jpg", detailCount: 5 },
    { id: 43, title: "스마일 라운드 맥주잔 2P", price: "22,900", img: "/img/cup2.jpg", detailCount: 5 },
    { id: 44, title: "그라데이션 고블렛 2P", price: "31,900", img: "/img/cup3.jpg", detailCount: 5 },
    { id: 45, title: "스태킹 이중 내열 글라스 유리컵 L 450ml", price: "14,900", img: "/img/cup4.jpg", detailCount: 5 },
    { id: 46, title: "스태킹 이중 내열 글라스 유리컵 S 250ml", price: "9,900", img: "/img/cup5.jpg", detailCount: 5 },
    { id: 47, title: "위스키 언더락잔 320ml", price: "11,900", img: "/img/cup6.jpg", detailCount: 5 },
    { id: 48, title: "위스키 글라스잔 200ml", price: "11,900", img: "/img/cup7.jpg", detailCount: 5 },
    { id: 49, title: "위스키 고블렛잔 210ml", price: "16,900", img: "/img/cup8.jpg", detailCount: 5 },
    { id: 50, title: "링 핸들 머그 M", price: "7,900", img: "/img/cup9.jpg", detailCount: 5 },
  ],
  "#블랑": [
    { id: 200, title: "블랑 앞접시 찬기 4종 세트", price: "44,900", img: "/img/bllang1.jpg", detailCount: 10 },
    { id: 52, title: "블랑 웨이브 2인 그릇세트 홈세트 12P", price: "99,000", img: "/img/bllang2.jpg", detailCount: 5 },
    { id: 53, title: "블랑 4인 그릇세트 홈세트 27P", price: "199,000", img: "/img/bllang3.jpg", detailCount: 5 },
    { id: 54, title: "블랑 플리츠 머그컵", price: "9,000", img: "/img/bllang4.jpg", detailCount: 5 },
    { id: 55, title: "블랑 웨이브 머그컵", price: "9,900", img: "/img/bllang5.jpg", detailCount: 5 },
    { id: 56, title: "블랑 플뢰르 접시 소", price: "15,000", img: "/img/bllang6.jpg", detailCount: 5 },
    { id: 57, title: "블랑 플리츠 접시 소", price: "15,000", img: "/img/bllang7.jpg", detailCount: 5 },
    { id: 58, title: "블랑 웨이브 접시 소", price: "15,000", img: "/img/bllang8.jpg", detailCount: 5 },
    { id: 59, title: "블랑 라비에 접시 소", price: "15,000", img: "/img/bllang9.jpg", detailCount: 5 },
  ],
  "#오딧세이": [
    { id: 60, title: "오딧세이 패딩 런치백 도시락가방 보냉백 (2color)", price: "28,710", img: "/img/ods1.jpg", detailCount: 5 },
    { id: 61, title: "오딧세이 런치백 (2 color)", price: "27,900", img: "/img/ods2.jpg", detailCount: 5 },
    { id: 62, title: "오딧세이 투고 텀블러 420ml (5color)", price: "21,900", img: "/img/ods3.jpg", detailCount: 5 },
    { id: 63, title: "오딧세이 런치박스 S (칸막이) (2color)", price: "16,900", img: "/img/ods4.jpg", detailCount: 5 },
    { id: 64, title: "오딧세이 런치박스 M (2 color)", price: "16,900", img: "/img/ods5.jpg", detailCount: 5 },
    { id: 65, title: "오딧세이 런치박스 세트(S+M)(컬러교차선택)", price: "29,900", img: "/img/ods6.jpg", detailCount: 5 },
    { id: 66, title: "오딧세이 런치박스 풀세트(런치박스S+M,런치백,도시락수저통)", price: "53,910", img: "/img/ods7.jpg", detailCount: 5 },
    { id: 67, title: "오딧세이 패딩 런치박스 풀세트(런치박스S+M+패딩런치백+휴대용수저세트)", price: "56,610", img: "/img/ods8.jpg", detailCount: 5 },
    { id: 68, title: "오딧세이 휴대용 도시락 수저포크 세트", price: "9,900", img: "/img/ods9.jpg", detailCount: 5 },
  ],
};